"""The published category table must be what the builder produces.

The first attempt at this data was generated by a script that never made it
into the repo, and it drifted: 24,057 of its 24,152 rows disagreed with what
the builder committed alongside it said, and every fruit and vegetable was
filed under facial skincare. Nothing caught it, because the file looked healthy
- sorted, deduplicated, one source per row, plausible counts.

So the guard is not "does the file look reasonable" but "does the checked-in
builder still produce the checked-in file, byte for byte". Anything generated
by hand, by a notebook or by an ad-hoc script fails here.

The rest are cheap invariants that the scrambled file would also have failed:
loose produce has to land in produce, and every category id has to exist.
"""

import json
import os
import subprocess
import sys

import pytest

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
DATA = os.path.join(ROOT, "data")
TSV = os.path.join(DATA, "product_categories.tsv")
TAXONOMY = os.path.join(DATA, "categories.json")


@pytest.fixture(scope="module")
def taxonomy():
    with open(TAXONOMY, encoding="utf-8") as handle:
        return json.load(handle)


@pytest.fixture(scope="module")
def rows():
    out = []
    with open(TSV, encoding="utf-8") as handle:
        for line in handle:
            barcode, category_id, source = line.rstrip("\n").split("\t")
            out.append((barcode, int(category_id), source))
    return out


class TestTheBuilderReproducesTheData:
    def test_rerunning_the_builder_changes_nothing(self, tmp_path):
        before = open(TSV, "rb").read(), open(TAXONOMY, "rb").read()
        subprocess.run(
            [sys.executable, os.path.join(ROOT, "scripts", "build_categories.py")],
            check=True, capture_output=True,
        )
        after = open(TSV, "rb").read(), open(TAXONOMY, "rb").read()
        assert before == after, (
            "the committed category data is not what scripts/build_categories.py "
            "produces - it was generated somewhere else and has drifted"
        )


class TestTheTaxonomyIsWellFormed:
    def test_every_row_points_at_a_category_that_exists(self, rows, taxonomy):
        known = {c["id"] for c in taxonomy}
        assert {r[1] for r in rows} <= known

    def test_products_hang_off_sub_categories_not_top_level(self, rows, taxonomy):
        top_level = {c["id"] for c in taxonomy if c["parent_id"] is None}
        assert not ({r[1] for r in rows} & top_level)

    def test_slugs_are_unique_and_ascii(self, taxonomy):
        slugs = [c["slug"] for c in taxonomy]
        assert len(slugs) == len(set(slugs))
        # A slug ends up in URLs and CSS class names; Hebrew inside one, as the
        # first attempt had, makes both awkward. The Hebrew lives in name_he.
        assert all(s.isascii() for s in slugs)

    def test_every_sub_category_has_a_real_parent(self, taxonomy):
        top_level = {c["id"] for c in taxonomy if c["parent_id"] is None}
        assert all(c["parent_id"] in top_level
                   for c in taxonomy if c["parent_id"] is not None)


class TestTheFileIsAppendable:
    def test_sorted_by_barcode(self, rows):
        # Sorted so a nightly run's new rows land as a small localised diff
        # rather than rewriting five megabytes.
        assert [r[0] for r in rows] == sorted(r[0] for r in rows)

    def test_one_row_per_barcode(self, rows):
        assert len({r[0] for r in rows}) == len(rows)

    def test_every_row_names_a_chain_we_actually_scraped(self, rows):
        import sys
        sys.path.insert(0, os.path.join(ROOT, "scripts"))
        import chain_maps
        known = set(chain_maps.BY_CHAIN) | {"shufersal", "tiv_taam"}
        assert {r[2] for r in rows} <= known

    def test_every_scraped_chain_contributed_something(self, rows):
        # A chain that silently stops matching its table is the failure this
        # catches: the build still succeeds, the file still looks healthy, and
        # thousands of placements quietly vanish.
        import sys
        sys.path.insert(0, os.path.join(ROOT, "scripts"))
        import chain_maps
        present = {r[2] for r in rows}
        for chain in chain_maps.BY_CHAIN:
            if os.path.exists(os.path.join(DATA, "chain_taxonomies", f"{chain}.json")):
                assert chain in present, f"{chain} placed nothing"


@pytest.fixture(scope="module")
def placed(rows):
    with open(os.path.join(DATA, "chain_taxonomies", "shufersal.json"),
              encoding="utf-8") as handle:
        raw = json.load(handle)["products"]
    return raw, {b: c for b, c, _ in rows}


class TestProduceIsProduce:
    """The specific failure this replaces: tomatoes filed under skincare."""

    def test_fruit_and_veg_land_under_produce(self, placed, taxonomy):
        raw, seen = placed
        parent = {c["id"]: c["parent_id"] for c in taxonomy}
        produce = next(c["id"] for c in taxonomy if c["slug"] == "produce")
        fresh = [b for b, v in raw.items()
                 if (v.get("second_level") or "").strip() == "פירות וירקות"
                 and b in seen]
        assert fresh, "no fresh produce in the scrape at all"
        # Not all of it: Shufersal shelves vegetable seeds here, and those are
        # deliberately routed to the garden aisle instead.
        under = [b for b in fresh if parent.get(seen[b]) == produce]
        assert len(under) / len(fresh) > 0.7
